### ISSUE TITLE
Examples crash on FATAL EXCEPTION: GLThread 4689

### ISSUE THREAD

**Issue by orgicus** [codeanticode/processing-cardboard#3]
I've recently installed version 0.6 of the cardboard library on Processing 3.2.3 and tried the Cube and Mono examples, but both crash with a similar error message:

```java
FATAL EXCEPTION: GLThread 4913
Process: processing.test.mono, PID: 13489
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vrtoolkit/cardboard/Viewport;
	at processing.cardboard.PGraphicsCardboard.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vrtoolkit.cardboard.Viewport" on path: DexPathList[[zip file "/data/app/processing.test.mono-2/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.mono-2/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 5 more
```

this error is on Android 7.1 (on a Google Pixel device).

Here's is a similar error with a few more details on Android 5.1.1 (on a Xperia Z device):
```java
OpenGL error 1280 at bot beginDraw(): invalid enum
OpenGL error 1280 at bot beginDraw(): invalid enum
OpenGL error 1280 at bot beginDraw(): invalid enum
FATAL EXCEPTION: GLThread 891
Process: processing.test.mono, PID: 11185
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vrtoolkit/cardboard/Viewport;
	at processing.cardboard.PGraphicsCardboard.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vrtoolkit.cardboard.Viewport" on path: DexPathList[[zip file "/data/app/processing.test.mono-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
FATAL EXCEPTION: GLThread 891
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
Process: processing.test.mono, PID: 11185
FATAL EXCEPTION: GLThread 891
	... 5 more
Process: processing.test.mono, PID: 11185
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vrtoolkit/cardboard/Viewport;
	at processing.cardboard.PGraphicsCardboard.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vrtoolkit.cardboard.Viewport" on path: DexPathList[[zip file "/data/app/processing.test.mono-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vrtoolkit/cardboard/Viewport;
	... 5 more
	Suppressed: java.lang.ClassNotFoundException: com.google.vrtoolkit.cardboard.Viewport
	Suppressed: java.lang.ClassNotFoundException: com.google.vrtoolkit.cardboard.Viewport
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 6 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
	at processing.cardboard.PGraphicsCardboard.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
		at java.lang.Class.classForName(Native Method)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 6 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vrtoolkit.cardboard.Viewport" on path: DexPathList[[zip file "/data/app/processing.test.mono-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 5 more
	Suppressed: java.lang.ClassNotFoundException: com.google.vrtoolkit.cardboard.Viewport
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 6 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available```

Any hints on what I might be missing ?

**Comment by codeanticode** [comment]
Hi, what version of the Android mode are you using? This library is meant to be used with versions 4.0-beta1 to beta2 of the mode (it is not compatible with the latest stable release available through the Contributions Manager). Versions 4.0-beta3 and newer bundle the carboard library, so you don't need to use this stand alone version anymore.

**Comment by codeanticode** [comment]
Closing as the stand-alone cardboard library is no longer developed. Please re-open in the processing-android repo if you still experience this issue with the [latest betas of the mode](https://github.com/processing/processing-android/releases). Thanks!

**Comment by orgicus** [comment]
Hello Andres,

Apologies for the delay, I forgot to report back.
Running the Cardboard library samples from the latest beta of the mode did indeed work! 
Thank you very much for your support.

If it's any help, after manually installing the latest beta of Android mode (4.0 beta5) I got prompted to re-locate the Android SDK. I pointed it to the same location (`~/android-sdk-macosx`), but it still didn't find it, perhaps because I was missing the SDK 25. I used the Android SDK Manager to install it and, restarted Processing and retried using Android Mode but I got the same error. 

In the end I gave up on trying to convince Android Mode that I do indeed have Android SDK 25 installed and left the mode download the SDK again itself. This worked and I could play with the Cardboard library :)

**Comment by codeanticode** [comment]
Thanks for reporting back. Yes, the latest beta requires the platform SDK for API 25, but that alone is not enough. It also needs the Android Support Repository (which includes the support libraries) and the Google repository (which includes the wear SDK).

Unfortunately, these additional packages increase the size of the download quite substantially, but there is no way around it, as we should not be bundling pieces of the SDK with the Android mode (it is not allowed by the Android License).
